# Generated by Django 6.0.3 on 2026-04-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='stock_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
